### ISSUE TITLE
[UI-Checklist] News

### ISSUE THREAD

**Issue by KannipaB** [KannipaB/toro-frontend#10]
# news-show

![screen shot 2016-06-16 at 3 02 42 pm](https://cloud.githubusercontent.com/assets/12539405/16109544/9cdb0638-33d3-11e6-825a-70807f08fe38.png)
- [x] ตรวจสอบ padding ระหว่างตัวอักษร headline กับ tag ด้านบนด้วยค่ะ
- [x] อย่าลืมแถบสีฟ้าข้างหน้าสุดของ content ด้วยนะคะ เข้าไปดูใน balltoro ของจริงจ่ะ
- [x] ตรวจสอบขนาดตัวอักษรด้วยนะคะว่าเท่ากับของเดิม
- [x] อย่าลืม breadcrumb นะฮะ

/ อันนี้เป็น checklist  กันลืมค่ะ ถ้าทำอันไหนเสร็จแล้วก็กดติ๊กได้เลย หรือถ้าใครจะเพิ่มอะไรก็คอมเมนต์เพิ่มเลย

@Tullaphat @SuperCipher
